services:
  - type: web
    name: album-copa-2026
    env: node
    region: oregon
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false   # set manually in Render dashboard
